[package]
name = "sdl01"
version = "0.1.0"
authors = ["Lukas Nagel <lukaswnagel@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.33.0"
